# Define a PVC.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remind-me-api-pv-claim
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---