# Define a PV.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-10gi-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/my-10gi-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-1gi-pvc
  labels:
    app: my-1gi-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  