apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replica: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: mysql
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
      initContainers:
      - name: init-mysql
        image: mysql:5.7
      - name: clone-mysql
        image: mysql:5.7
      containers:
