# kubectl run alpine-sh --rm -it --image=alpine:3.16 -- sh
# kubectl run -i --rm --tty debug --image=alpine:3.16 --restart=Never -- sh
apiVersion: v1
kind: Pod
metadata:
  name: my-alpine
spec:
  containers:
  - image: alpine:3.16
    name: alpine
