# Run one of the following to run
# kubectl run alpine-sh --rm -it --image=alpine:3.16 -- sh
# kubectl run -i --rm --tty debug --image=alpine:3.16 --restart=Never -- sh
apiVersion: v1
kind: Pod
metadata:
  name: my-alpine
spec:
  restartPolicy: "Never"
  volumes:
  - name: fileshare-storage
    persistentVolumeClaim:
      claimName: fileshare-pv-claim
  containers:
  - image: alpine:3.16
    name: alpine
    stdin: true
    tty: true
    # command: ["sh"]
    volumeMounts:
    - name: fileshare-storage
      mountPath: /mnt/data
