# Run one of the following to run
# kubectl run alpine-sh --rm -it --image=alpine:3.16 -- sh
# kubectl run -i --rm --tty debug --image=alpine:3.16 --restart=Never -- sh
apiVersion: v1
kind: Pod
metadata:
  name: my-alpine1
spec:
  restartPolicy: "Never"
  volumes:
  - name: fileshare-storage
    persistentVolumeClaim:
      claimName: my-1gi-pvc
  containers:
  - image: alpine:3.16
    name: alpine
    # stdin: true
    # tty: true
    # command: ["sh"]
    command: [ 'sh', '-c', 'sleep infinite']
    volumeMounts:
    - name: fileshare-storage
      mountPath: /mnt/data
