apiVersion: v1
kind: Pod
metadata:
  name: my-rabbitmq
spec:
  containers:
  - image: rabbitmq:3.10-management
    name: rabbitmq
    ports:
    - name: http
      containerPort: 80
    resources:
      requests:
        memory: 100M
        cpu: "0.25"
      limits:
        memory: 100M
        cpu: "0.50"