apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: everymin
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: everymin
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: alpine:3.16
            name: everymin
            resources: {}
            command: [ "sh", "-c", "date; echo Hello from the Kubernetes cluster"]
          restartPolicy: OnFailure
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
status: {}
