# Define a PV.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileshare-5gi-pv
  labels:
    type: local
    environment: dev
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/fileshare-5gi-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devenv
  name: generic-128mi
  labels:
    app: generic
    environment: dev
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
