apiVersion: batch/v1
kind: Job
metadata:
  namespace: devenv
  name: echojob
spec:
  template:
    spec:
      containers:
      - name: alpine-echo
        image: alpine:3.16
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret2
              key: PASSWORD
        command: [ "sh", "-c", "date; echo Hello from the Kubernetes cluster $MYSQL_ROOT_PASSWORD"]
      restartPolicy: Never
  backoffLimit: 1
