apiVersion: batch/v1
kind: Job
metadata:
  namespace: devenv
  name: echojob
spec:
  template:
    spec:
      volumes:
        - name: cloud-amqp-secret
          secret:
            secretName: cloud-amqp-secret
            items:
            - key: .cloudampq.json
              path: .cloudampq.json
            optional: false # default setting; "mysecret" must exist
      containers:
      - name: alpine-echo
        image: alpine:3.16
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: PASSWORD
        volumeMounts:
        - name: cloud-amqp-secret
          mountPath: "/mnt/secrets"
          readOnly: true
        command: [ "sh", "-c", "date; cat /mnt/secrets/.cloudampq.json; echo all ok $MYSQL_ROOT_PASSWORD "]
      restartPolicy: Never
  backoffLimit: 1
