apiVersion: batch/v1
kind: Job
metadata:
  namespace: devenv
  name: dj
spec:
  backoffLimit: 1
  template:
    spec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      volumes:
      - name: cloud-amqp-secret
        secret:
          secretName: cloud-amqp-secret
          items:
          - key: .cloudampq.json
            path: cloud-amqp/.cloudampq.json
          optional: false # default setting; "mysecret" must exist
      containers:
      - image: dumpy:v1
        name: dum
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: PASSWORD
        volumeMounts:
        - name: cloud-amqp-secret
          mountPath: "/mnt/secrets"
          readOnly: true
        # command: [ "sh", "-c", "date; cat /mnt/secrets/.cloudampq.json; echo all ok $MYSQL_ROOT_PASSWORD "]
