# Define a PV.
# Volume mount usage layout
# /usr/share/generic-128mi
# ├───/instrument
# │   ├───/asx
# │   │   ├───asx-isin-20220909-030601.txt
# │   │   └───asx-isin-20220909-030601.txt
# │   └───/sgx
# │       └───sgx-isin-20220909-030601.txt
# ├───/yahoo-finance
# │   └───/sgx
# │       └───sgx-isin-20220909-030601.txt
# └───/sql
#     ├───01-database.sql  
#     └───02-instrument_type.sql
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: devenv
  name: generic-128mi-pv
  labels:
    type: local
    environment: dev
spec:
  storageClassName: hostpath
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/generic-128mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devenv
  name: generic-128mi-pvc
  labels:
    app: generic
    environment: dev
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
