# Define a PV.
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: devenv
  name: mysql-pv
  labels:
    type: local
    app: mysql
    environment: dev
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devenv
  name: mysql-pvc
  labels:
    app: mysql
    environment: dev
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  